behaviors:
  AnimalAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 2024
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
      goal_conditioning_type: hyper
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
        network_settings:
          normalize: false
          hidden_units: 128
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
      curiosity:
        gamma: 0.99
        strength: 0.01
        network_settings:
          normalize: false
          hidden_units: 256
          num_layers: 2
          vis_encode_type: simple
          goal_conditioning_type: hyper
        learning_rate: 0.0003
        encoding_size: 256
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 10000
    threaded: false
