!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 250
    items:
    - !Item
      name: Agent
      rotations: [0]
      positions:
      - !Vector3 {x: 20, y: 0, z: 20}
    - !Item
      name: Cardbox1
      positions:
      - !Vector3 {x: 5, y: 0, z: 2.5}      
      - !Vector3 {x: 13.75, y: 0, z: 2.5}
      - !Vector3 {x: 5, y: 0, z: 10}      
      - !Vector3 {x: 13.75, y: 0, z: 10}
      - !Vector3 {x: 5, y: 0, z: 20}      
      - !Vector3 {x: 13.75, y: 0, z: 20}
      - !Vector3 {x: 5, y: 0, z: 30}      
      - !Vector3 {x: 13.75, y: 0, z: 30}
      rotations: [0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 5, z: 5}
      - !Vector3 {x: 7.5, y: 5, z: 5}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
    - !Item
      name: Cardbox1
      positions:
      - !Vector3 {x: 35, y: 0, z: 2.5}      
      - !Vector3 {x: 26.25, y: 0, z: 2.5}
      - !Vector3 {x: 35, y: 0, z: 10}      
      - !Vector3 {x: 26.25, y: 0, z: 10}
      - !Vector3 {x: 35, y: 0, z: 20}      
      - !Vector3 {x: 26.25, y: 0, z: 20}
      - !Vector3 {x: 35, y: 0, z: 30}      
      - !Vector3 {x: 26.25, y: 0, z: 30}
      rotations: [0,0,0,0,0,0,0,0]
      sizes:
      - !Vector3 {x: 10, y: 5, z: 5}
      - !Vector3 {x: 7.5, y: 5, z: 5}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
      - !Vector3 {x: 10, y: 5, z: 10}
      - !Vector3 {x: 7.5, y: 5, z: 10}
    - !Item
      name: GoodGoal
      positions:
      - !Vector3 {x: 5, y: 0, z: 37.5}
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}